version: "3.8"

services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - backend-db:/var/lib/mongodb/data

  webapp:
    build:
      context: ./webapp
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/opt/app
    environment:
      REACT_APP_BACKEND_PORT: "3000"
    restart: always

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/opt/app
    depends_on:
      - database
    restart: always

volumes:
  backend-db:
