version: "3.8"

services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - backend-db:/var/lib/mongodb/data

  webapp:
    image: ${WEBAPP_IMAGE}
    ports:
      - "80:3000"
    environment:
      REACT_APP_BACKEND_PORT: "4000"
    restart: always

  api:
    image: ${API_IMAGE}
    ports:
      - "4000:5000"
    depends_on:
      - database
    restart: always

volumes:
  backend-db:
